[template]
src = "hazelcast.tmpl"
dest = "/opt/hazelcast/hazelcast.xml"
keys = [
  "/self/service",
  "/containers",
  "/services",
]
check_cmd = "/etc/confd/bin/check.sh {{ .src }}"
reload_cmd = "echo RELOAD !!"