[template]
src = "hazelcast.tmpl"
dest = "/opt/hazelcast/hazelcast.xml"
keys = [
  "/self/service",
  "/containers",
  "/services",
]

# reload_cmd = "/opt/hazelcast/stop.sh && /opt/hazelcast/start.sh"